### PR TITLE
fix Invalid or unexpected token

### PR DESCRIPTION
**Pull request by ganeshrvel**
Fix the error `Invalid or unexpected token` caused by `#!/usr/bin/env node`

Error:
```js
Uncaught /path/node_modules/koffi/src/koffi/src/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                                                                                                                           ^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (node:electron/js2c/renderer_init:33:356)
```

Screenshot 2023-01-13 at 12 40 07 AM

### CODE REVIEW

**Comment by Koromix** [comment]
Thanks!

**Comment by ganeshrvel** [comment]
Hey @Koromix could you release beta.5, I was planning to send my app for a private beta testing tonight. The bundler issue is stopping me from doing so.

Thanks

**Comment by Koromix** [comment]
The build script is running :) It'll come in a few minutes ;)

image

**Comment by Koromix** [comment]
2.2.2-beta.5 is published ;)

**Pull request merged**
