### PR TITLE
Fix some TypeScript definitions

### PR DESCRIPTION
**Pull request by insraq**
I've fixed some TypeScript definitions - the old one has some inaccuracies.

Also, apologize for the code style change - the repo doesn't have prettier config so it uses my default editor config (which is different across my machines)

### CODE REVIEW

**Comment by Koromix** [comment]
Thanks! I've imported some of your changes manually.

However, as far as "as" and "decode" are involved, non-record values can be used and/or returned:
- you can decode a double, or a pointer, etc.
- You can use cast (as) external objects, buffers, objects, etc.

So I've used "unknown" for these functions.

Here is the file right now:
https://github.com/Koromix/rygel/blob/master/src/koffi/src/index.d.ts

Do it look okay to you?

**Comment by insraq** [comment]
I wouldn't use `unknown` since it requires a special cast. Use `any` in that case. However, If possible, specifying the type using union type would be a better choice. Something like: "Buffer | Record<string, unknown>" or "number | string | Record<string, unknown>" would probably be better?

`Record<string, unknown>` actually means any JavaScript object - I don't usually use it as it is quite a mouthful but my ESLint linter tells me to use that syntax :-) https://www.reddit.com/r/typescript/comments/tq3m4f/the_difference_between_object_and_recordstring/

**Comment by Koromix** [comment]
I've switched to any!

For `decode` and `as`, and when it comes to type systems, I'm very much in the "80% is enough" team, and prefer to use an escape instead of trying to specify everything through the type system.

But I'll keep it in mind and maybe improve the definition later on.

**Comment by insraq** [comment]
Feel free to close this PR if you have incorporated the changes. Which release would type definitions be included? Currently I am using my own typings and I'd like to switch to the repo version

**Comment by Koromix** [comment]
It's available and published in Koffi 2.3.1, with the fixes (in theory) ;)

You can always find the changelog here when I push a new version (or inside the package: CHANGELOG.md):
https://koffi.dev/changelog

**Pull request closed without merging**
